### ISSUE TITLE
Ban note restore does not work properly due to method modification

### ISSUE THREAD

**Issue by blankdvth** [blankdvth/eGOScripts#8]
On the newest version (as of PR #2), the mousedown event that restores the span to the old version without URLs does not work correctly. Current theory is that it is a result of the move from `banNotes.forEach` to `for (let banNote of banNotes) {` causing the variables to point to the wrong location in the mousedown callback, although this is uncertain as the issue seems to cause the element to get updated properly, but too late (much like using onclick would cause).

The [version prior to the change](https://github.com/blankdvth/eGOScripts/blob/b09ceca924b769992ba55a549505dd7d3823c488/EdgeGamers%20MAUL%20Enhancement.user.js) does work properly and as expected.

**Comment by SkleKng** [comment]
Fixed in PR #9
